name: sos_battery
description: SOS-BATTERY - Real-time battery rescue across USA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Phiên bản ổn định nhất 2025)
  firebase_core: ^3.10.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.2.0

  # State management (Riverpod 3.x mới nhất)
  flutter_riverpod: ^3.0.3

  # Routing
  go_router: ^14.7.0

  # Maps & Location
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.0 # Dùng bản mới nhất để thay thế hoàn toàn background_locator_2
  google_sign_in: ^6.2.1  # version mới nhất 2025

  # Background service (Giải pháp chạy ngầm tốt nhất hiện nay)
  # Dùng kết hợp cái này với geolocator để lấy vị trí ngầm mà không bị lỗi Namespace
  flutter_background_service: ^5.1.0 

  # UI & Animation
  confetti: ^0.8.0
  lottie: ^3.3.0
  flutter_local_notifications: ^18.0.1 

  # Utils
  url_launcher: ^6.3.1  
  shared_preferences: ^2.5.0
  package_info_plus: ^8.2.0
  http: ^1.3.0  
  flutter_foreground_task: ^9.1.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Lưu ý: Nếu bạn có file assets (ảnh, icon SOS, lottie), hãy khai báo thêm ở dưới này:
  # assets:
  #   - assets/images/
  #   - assets/animations/
  assets:
    - assets/icons/iconsos.png
    - assets/icons/logososclear.png  # tên file logo mới của bro
